name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Set up environment variables
      run: echo "VARIABLE_NAME=${{ secrets.OPEN_WEATHER_KEY }}" >> $GITHUB_ENV

    - name: Start the server
      run: |
        npm run dev > /tmp/server.log 2>&1 &
        echo "Server is starting..."
      env:
        VARIABLE_NAME: ${{ secrets.OPEN_WEATHER_KEY }}

    - name: Wait for server to be ready
      run: npx wait-on http://localhost:3000 --timeout 300000

    - name: Run tests
      run: npm run test:jest

    - name: Print server logs for debugging
      run: |
        echo "Server logs:"
        cat /tmp/server.log